services:
  - type: web
    name: eventus-bot
    env: python
    plan: organization
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python eventus_render_mega.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    autoDeploy: false
